#!/usr/bin/env python3
"""Write docs/references.md from the registry and build/measure-<key>.json (run scripts/measure_references.py first)."""
from __future__ import annotations

import json
import sys
from pathlib import Path

import _path  # noqa: F401
from waffle_eda.bench import references as refs

CLASS_TITLES = {
    "A": "Class A: two layers, a microcontroller or module, passives, headers",
    "B": "Class B: four layers, fine-pitch QFN or small FPGA, USB, regulators, ground planes",
    "B+": "Class B+: a BGA on four to six layers, no DDR bus (or a slow one)",
    "C": "Class C: BGA FPGA with a DDR3 bus",
    "C'": "Class C': BGA FPGA with HyperRAM, no DDR3",
}


def main() -> int:
    build = refs.repo_root() / "build"
    out = ["# Reference boards, measured", "",
           "Generated by `scripts/report_references.py` from `waffle_eda/bench/references.toml` and the measurements in",
           "`build/measure-<key>.json` (pcbnew 9). Every number here is evidence for a rule in `definition.md` or a",
           "decision in `decisions.md`; nothing in the boards themselves is committed to this repository.", ""]
    missing = []
    for cls in refs.CLASSES:
        rows = refs.by_class(cls)
        if not rows:
            continue
        out += [f"## {CLASS_TITLES[cls]}", "",
                "| Key | Board | Layers | Size mm | Footprints | Nets | Min track mm | Licence | Source |",
                "|---|---|---|---|---|---|---|---|---|"]
        for ref in rows:
            path = build / f"measure-{ref.key}.json"
            if not path.is_file():
                missing.append(ref.key)
                continue
            d = json.loads(path.read_text())
            repo = ref.repo.removesuffix(".git")
            out.append(
                f"| `{ref.key}` | {ref.notes} | {len(d['copper_layers'])} | {d['outline_mm'][0]:.0f} x {d['outline_mm'][1]:.0f} | "
                f"{d['footprints']} | {d['nets']} | {d['min_track_mm']} | {ref.licence} | [{ref.attribution}]({repo}) at `{ref.commit[:10]}`, `{ref.board}` |"
            )
        out.append("")
        bus_rows = [r for r in rows if r.has_bus and (build / f"measure-{r.key}.json").is_file()]
        if bus_rows:
            out += ["Bus copper, measured on the boards above that have one:", "",
                    "| Key | Bus nets (pattern) | Between | Vias, inside the packages | Vias per net | Length mm min / median / max | Layers (nets using) | Bus track widths mm |",
                    "|---|---|---|---|---|---|---|---|"]
            for ref in bus_rows:
                d = json.loads((build / f"measure-{ref.key}.json").read_text())
                b = d["bus"]
                share = f"{100 * b['vias_in_packages'] / b['vias_total']:.0f} %" if b["vias_total"] else "n/a"
                vias_per_net = ", ".join(f"{k}: {v}" for k, v in b["vias_per_net_hist"].items())
                layers = ", ".join(f"{k} {v}" for k, v in b["layers_used"].items())
                widths = ", ".join(f"{w} ({n})" for w, n in b["track_widths_mm"][:3])
                offsets = "; ".join(f"{k} at ({x}, {y})" for k, (x, y) in d.get("part_offsets_mm", {}).items())
                between = f"{', '.join(ref.bus_parts)}" + (f" ({offsets} mm from {ref.bus_parts[0]})" if offsets else "")
                L = b["length_mm"]
                out.append(
                    f"| `{ref.key}` | {b['net_count']} (`{ref.bus_net_pattern}`) | {between} | {b['vias_total']}, {b['vias_in_packages']} ({share}) | "
                    f"{vias_per_net} | {L['min']} / {L['median']} / {L['max']} | {layers} | {widths} |"
                )
            out.append("")
    if missing:
        out += [f"Not yet measured: {', '.join(missing)}.", ""]
    (refs.repo_root() / "docs" / "references.md").write_text("\n".join(out))
    print("wrote docs/references.md;", "missing:" if missing else "all measured", missing or "")
    return 0


if __name__ == "__main__":
    sys.exit(main())
